framework:
    messenger:
        transports:
            sync: 'sync://'

        routing:
            App\Message\Command\PlayAllRoundsCommand: sync
            App\Message\Command\PlayNextRoundCommand: sync
            App\Message\Command\ResetToNewScheduleCommand: sync
